%LET N_DAYS = 365;
%LET DIAGNOSED_RATE = 1.0;
%LET S = 4390484;
%LET E = 0;
%LET I = 459.770114942528;
%LET R = 0;
%LET BETA = 5.013728017813E-8;
%LET BETA_DECAY = 0;
%LET SIGMA = 0.90;
%LET GAMMA = 0.07142857142857;
%LET IncubationPeriod = 0;
%LET DAY_ZERO = 13MAR2020;
%LET HOSP_RATE = 0.075;
%LET MARKET_SHARE = .29 ;
%LET HOSP_LOS = 7;

DATA DS_SEIR;
	DO DAY = 0 TO &N_DAYS;
		IF DAY = 0 THEN DO;
			S_N = &S - (&I/&DIAGNOSED_RATE) - &R;
			E_N = &E;
			I_N = &I/&DIAGNOSED_RATE;
			R_N = &R;
			BETA=&BETA;
			N = SUM(S_N, E_N, I_N, R_N);
		END;
		ELSE DO;
			BETA = LAG_BETA * (1- &BETA_DECAY);
			S_N = (-BETA * LAG_S * LAG_I) + LAG_S;
			E_N = (BETA * LAG_S * LAG_I) - &SIGMA * LAG_E + LAG_E;
			I_N = (&SIGMA * LAG_E - &GAMMA * LAG_I) + LAG_I;
			R_N = &GAMMA * LAG_I + LAG_R;
			N = SUM(S_N, E_N, I_N, R_N);
			SCALE = LAG_N / N;
			IF S_N < 0 THEN S_N = 0;
			IF E_N < 0 THEN E_N = 0;
			IF I_N < 0 THEN I_N = 0;
			IF R_N < 0 THEN R_N = 0;
			S_N = SCALE*S_N;
			E_N = SCALE*E_N;
			I_N = SCALE*I_N;
			R_N = SCALE*R_N;
		END;
		LAG_S = S_N;
		LAG_E = E_N;
		LAG_I = I_N;
		LAG_R = R_N;
		LAG_N = N;
		LAG_BETA = BETA;
		NEWINFECTED=LAG&IncubationPeriod(SUM(LAG(SUM(S_N,E_N)),-1*SUM(S_N,E_N)));
		IF NEWINFECTED < 0 THEN NEWINFECTED=0;
        HOSP = NEWINFECTED * &HOSP_RATE * &MARKET_SHARE;
        CUMULATIVE_SUM_HOSP + HOSP;
        CUMADMITLAGGED=ROUND(LAG&HOSP_LOS(CUMULATIVE_SUM_HOSP),1) ;
        HOSPITAL_OCCUPANCY= ROUND(CUMULATIVE_SUM_HOSP-CUMADMITLAGGED,1);
        DATE = "&DAY_ZERO"D + DAY;
		OUTPUT;
    END;
RUN;

PROC SGPLOT DATA=DS_SEIR;
    SERIES X=DATE Y=HOSPITAL_OCCUPANCY / LINEATTRS=(THICKNESS=2);
    XAXIS LABEL="Date";
    YAXIS LABEL="Daily Occupancy";
RUN;

DATA DS_SEIR_SIM;
    call streaminit(2019);
    DO SIM = 1 to 1000;
        DO DAY = 0 TO &N_DAYS;
            IF DAY = 0 THEN DO;
                S_N = &S - (&I/&DIAGNOSED_RATE) - &R;
                E_N = &E;
                I_N = &I/&DIAGNOSED_RATE;
                R_N = &R;
                BETA=&BETA;
                N = SUM(S_N, E_N, I_N, R_N);
            END;
            ELSE DO;
                BETA = LAG_BETA * (1- &BETA_DECAY);
                RV = RAND('POISSON',BETA * LAG_S * LAG_I);
                S_N = (-RV) + LAG_S;
                E_N = (RV) - &SIGMA * LAG_E + LAG_E;
                I_N = (&SIGMA * LAG_E - &GAMMA * LAG_I) + LAG_I;
                R_N = &GAMMA * LAG_I + LAG_R;
                N = SUM(S_N, E_N, I_N, R_N);
                SCALE = LAG_N / N;
                IF S_N < 0 THEN S_N = 0;
                IF E_N < 0 THEN E_N = 0;
                IF I_N < 0 THEN I_N = 0;
                IF R_N < 0 THEN R_N = 0;
                S_N = SCALE*S_N;
                E_N = SCALE*E_N;
                I_N = SCALE*I_N;
                R_N = SCALE*R_N;
            END;
            LAG_S = S_N;
            LAG_E = E_N;
            LAG_I = I_N;
            LAG_R = R_N;
            LAG_N = N;
            LAG_BETA = BETA;

            DATE = "&DAY_ZERO"D + DAY;
            OUTPUT;
        END;
    END;
RUN;
DATA DS_SEIR_SIM;
	SET DS_SEIR_SIM;
            NEWINFECTED=LAG&IncubationPeriod(SUM(LAG(SUM(S_N,E_N)),-1*SUM(S_N,E_N)));
            IF NEWINFECTED < 0 THEN NEWINFECTED=0;
            HOSP = NEWINFECTED * &HOSP_RATE * &MARKET_SHARE;
            CUMULATIVE_SUM_HOSP + HOSP;
            CUMADMITLAGGED=ROUND(LAG&HOSP_LOS(CUMULATIVE_SUM_HOSP),1) ;
            HOSPITAL_OCCUPANCY= ROUND(CUMULATIVE_SUM_HOSP-CUMADMITLAGGED,1);
run;

PROC SGPLOT DATA=DS_SEIR_SIM;
	where sim<20;
    SERIES X=DATE Y=HOSPITAL_OCCUPANCY / LINEATTRS=(THICKNESS=2) GROUP=SIM;
    XAXIS LABEL="Date";
    YAXIS LABEL="Daily Occupancy";
RUN;

