%EASYRUN inputs:
    scenario=Scenario_DrS_00_20_run_1,
    IncubationPeriod=0,
    InitRecovered=0,
    RecoveryDays=14,
    doublingtime=5,
    KnownAdmits=10,
    KnownCOVID=46,
    Population=4390484,
    SocialDistancing=0,
    MarketSharePercent=0.29,
    Admission_Rate=0.075,
    ICUPercent=0.45,
    VentPErcent=0.35,
    ISOChangeDate='31MAR2020'd,
    SocialDistancingChange=0,
    ISOChangeDateTwo='06APR2020'd,
    SocialDistancingChangeTwo=0.2,
    FatalityRate=0,
    plots=YES	

Adjustments parameters.sas:

DS SIR:
    - &Scenario (%EasyRun)
    - &N_DAYS (parameters.sas)
        - hardcoded
    - &S (parameters.sas)
        - &S_DEFAULT (parameters.sas)
            - &Population (%EasyRun)
    - &I (parameters.sas)
        - %SYSEVALF(&INITIAL_INFECTIONS / &DETECTION_PROB) (parameters.sas)
            - &INITIAL_INFECTIONS (parameters.sas)
                - &KNOWN_INFECTIONS (parameters.sas)
                    - &KnownCOVID. (%EasyRun)
            - &DETECTION_PROB (parameters.sas)
                - %SYSEVALF(&INITIAL_INFECTIONS / &TOTAL_INFECTIONS) (parameters.sas)
                    - &INITIAL_INFECTIONS (parameters.sas)
                        - &KNOWN_INFECTIONS (parameters.sas)
                            - &KnownCOVID. (%EasyRun)
                    - &TOTAL_INFECTIONS (parameters.sas)
                        - %SYSEVALF(&CURRENT_HOSP / &MARKET_SHARE / &HOSP_RATE)
                            - &CURRENT_HOSP (parameters.sas)
                                - &KNOWN_CASES (parameters.sas)
                                    - &KnownAdmits (%EasyRun)
                            - &MARKET_SHARE (parameters.sas)
                                - &MarketSharePercent. (%EasyRun)
                            - &HOSP_RATE (parameters.sas)
                                - %SYSEVALF(&ADMISSION_RATE*&DIAGNOSED_RATE)
                                    - &ADMISSION_RATE (parameters.sas)
                                        - &Admission_Rate (parameters.sas)
                                            - hardcoded
                                    - &DIAGNOSED_RATE (parameters.sas)
                                        - hardcoded
    - &R (parameters.sas)
        - &InitRecovered (%EasyRun)
    - &DIAGNOSED_RATE (parameters.sas)
        - hardcoded
    - &BETA (parameters.sas)
        - %SYSEVALF((&INTRINSIC_GROWTH_RATE + &GAMMA) / &S * (1-&RELATIVE_CONTACT_RATE)) (parameters.sas)
            - &INTRINSIC_GROWTH_RATE (parameters.sas)
                - %SYSEVALF(2 ** (1 / &DOUBLING_TIME) - 1) (parameters.sas)
                    - &DOUBLING_TIME (parameters.sas)
                        - &doublingtime (%EasyRun)
            - &GAMMA (parameters.sas)
                - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
                    - &RECOVERY_DAYS (parameters.sas)
                        - &RecoveryDays (%EasyRun)
            - &S (parameters.sas)
                - &S_DEFAULT (parameters.sas)
                    - &Population (%EasyRun)
            - &RELATIVE_CONTACT_RATE (parameters.sas)
                - &SocialDistancing (%EasyRun)
    - &GAMMA (parameters.sas)
        - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
            - &RECOVERY_DAYS (parameters.sas)
                - &RecoveryDays (%EasyRun)
    - &ISO_Change_Date (parameters.sas)
        - &ISOChangeDate (&EasyRun)
    - &BETA_Change (parameters.sas)
        - %SYSEVALF((&INTRINSIC_GROWTH_RATE + &GAMMA) / &S * (1-&RELATIVE_CONTACT_RATE_Change)) (parameters.sas)
            - &INTRINSIC_GROWTH_RATE (parameters.sas)
                - %SYSEVALF(2 ** (1 / &DOUBLING_TIME) - 1) (parameters.sas)
                    - &DOUBLING_TIME (parameters.sas)
                        - &doublingtime (%EasyRun)
            - &S (parameters.sas)
                - &S_DEFAULT (parameters.sas)
                    - &Population (%EasyRun)
            - &RELATIVE_CONTACT_RATE_Change (parameters.sas)
                - &SocialDistancing (%EasyRun)
    - &ISO_Change_Date_Two (parameters.sas)
        - &ISOChangeDateTwo (%EasyRun)
    - &BETA_CHANGE_Two (parameters.sas)
        - %SYSEVALF((&INTRINSIC_GROWTH_RATE + &GAMMA) / &S * (1-&RELATIVE_CONTACT_RATE_Change_Two)) (parameters.sas)
            - &INTRINSIC_GROWTH_RATE (parameters.sas)
                - %SYSEVALF(2 ** (1 / &DOUBLING_TIME) - 1) (parameters.sas)
                    - &DOUBLING_TIME (parameters.sas)
                        - &doublingtime (%EasyRun)
            - &GAMMA (parameters.sas)
                - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
                    - &RECOVERY_DAYS (parameters.sas)
                        - &RecoveryDays (%EasyRun)
            - &S (parameters.sas)
                - &S_DEFAULT (parameters.sas)
                    - &Population (%EasyRun)
            - &RELATIVE_CONTACT_RATE_Change_Two (parameters.sas)
                - &SocialDistancingChangeTwo (%EasyRun)

DS SEIR:
    - &E (parameters.sas)
        - hardcoded
    - &R_T (parameters.sas)
        - %SYSEVALF(&BETA / &GAMMA * &S) (parameters.sas)
            - &BETA (parameters.sas)
                - %SYSEVALF((&INTRINSIC_GROWTH_RATE + &GAMMA) / &S * (1-&RELATIVE_CONTACT_RATE)) (parameters.sas)
                    - &INTRINSIC_GROWTH_RATE (parameters.sas)
                        - %SYSEVALF(2 ** (1 / &DOUBLING_TIME) - 1) (parameters.sas)
                            - &DOUBLING_TIME (parameters.sas)
                                - &doublingtime (%EasyRun)
                    - &GAMMA (parameters.sas)
                        - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
                            - &RECOVERY_DAYS (parameters.sas)
                                - &RecoveryDays (%EasyRun)
                    - &S (parameters.sas)
                        - &S_DEFAULT (parameters.sas)
                            - &Population (%EasyRun)
                    - &RELATIVE_CONTACT_RATE (parameters.sas)
                        - &SocialDistancing (%EasyRun)
            - &GAMMA (parameters.sas)
                - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
                    - &RECOVERY_DAYS (parameters.sas)
                        - &RecoveryDays (%EasyRun)
            - &S (parameters.sas)
                - &S_DEFAULT (parameters.sas)
                    - &Population (%EasyRun)
    - &R_T_Change (parameters.sas)
        - %SYSEVALF(&BETA_Change / &GAMMA * &S) (parameters.sas)
            - &BETA_Change (parameters.sas)
                - %SYSEVALF((&INTRINSIC_GROWTH_RATE + &GAMMA) / &S * (1-&RELATIVE_CONTACT_RATE_Change)) (parameters.sas)
                    - &INTRINSIC_GROWTH_RATE (parameters.sas)
                        - %SYSEVALF(2 ** (1 / &DOUBLING_TIME) - 1) (parameters.sas)
                            - &DOUBLING_TIME (parameters.sas)
                                - &doublingtime (%EasyRun)
                    - &S (parameters.sas)
                        - &S_DEFAULT (parameters.sas)
                            - &Population (%EasyRun)
                    - &RELATIVE_CONTACT_RATE_Change (parameters.sas)
                        - &SocialDistancing (%EasyRun)
            - &GAMMA (parameters.sas)
                - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
                    - &RECOVERY_DAYS (parameters.sas)
                        - &RecoveryDays (%EasyRun)
            - &S (parameters.sas)
                - &S_DEFAULT (parameters.sas)
                    - &Population (%EasyRun)
    - &R_T_Change_Two (parameters.sas)
        - %SYSEVALF(&BETA_Change_Two / &GAMMA * &S) (parameters.sas)
            - &BETA_Change_Two
                - %SYSEVALF((&INTRINSIC_GROWTH_RATE + &GAMMA) / &S * (1-&RELATIVE_CONTACT_RATE_Change_Two)) (parameters.sas)
                    - &INTRINSIC_GROWTH_RATE (parameters.sas)
                        - %SYSEVALF(2 ** (1 / &DOUBLING_TIME) - 1) (parameters.sas)
                            - &DOUBLING_TIME (parameters.sas)
                                - &doublingtime (%EasyRun)
                    - &GAMMA (parameters.sas)
                        - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
                            - &RECOVERY_DAYS (parameters.sas)
                                - &RecoveryDays (%EasyRun)
                    - &S (parameters.sas)
                        - &S_DEFAULT (parameters.sas)
                            - &Population (%EasyRun)
                    - &RELATIVE_CONTACT_RATE_Change_Two (parameters.sas)
                        - &SocialDistancingChangeTwo (%EasyRun)
            - &GAMMA (parameters.sas)
                - %SYSEVALF(1/&RECOVERY_DAYS) (parameters.sas)
                    - &RECOVERY_DAYS (parameters.sas)
                        - &RecoveryDays (%EasyRun)
            - &S (parameters.sas)
                - &S_DEFAULT (parameters.sas)
                    - &Population (%EasyRun)
    - &SIGMA (parameters.sas)
        - hardcoded