export default {
	SELECT_PROJECT: 'SELECT_PROJECT',
	FETCH_SINGLE_PROJECT: "FETCH_SINGLE_PROJECT",
	CHANGES_SAVED: "CHANGES_SAVED",
	UPDATE_PROJECT: "UPDATE_PROJECT",
	OVERRIDE: "OVERRIDE",
	SET_SCENARIO: 'SET_SCENARIO',
	REMOVE_SCENARIO: 'REMOVE_SCENARIO',
	CLONE_SCENARIO: 'CLONE_SCENARIO'
}
